apiVersion: apps/v1
kind: Deployment
metadata:
  name: Station
  labels:
    app: Station
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Station
  template:
    metadata:
      labels:
        app: Station
    spec:
      containers:
        - name: Station
          image: username/Station:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5